platform = "asrock/paul"
arch = "arm"
toolchain = "arm-none-eabi-"
soc = "ast2500"
vendor = "aspeed"

[bootloader]
type = "u-boot"
fetch_cmd = "git clone --single-branch --depth=1 --branch v2019.04-aspeed-openbmc https://github.com/openbmc/u-boot src"
config = "aspeed/ast2500/u-boot/aspeed_g5_defconfig"

[kernel]
type = "linux"
fetch_cmd = "git clone --single-branch --depth=1 --branch dev-6.5 https://github.com/openbmc/linux src"
config = "aspeed/ast2500/linux/aspeed_g5_defconfig"
initrd_goflags = "GOARCH=arm GOARM=5 -a -ldflags='-s -w -buildid=' -gcflags=all=-l -trimpath"
custom_dt = true
dt = "aspeed/ast2500/linux/aspeed-ast2500-u-bmc.dts"

[image]
flash_size = "32M"
bootloader_offset = "0"
rootfs_offset = "832"
ab_scheme = false
