name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
     - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          check-latest: true
      - name: Run Build-Pipeline
        run: |
          make configure TARGET=asrock/paul
          make build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output/asrock/paul/flash.img
