name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          check-latest: true
      - name: Build ASRock Platform
        working-directory: targets/mainboards/asrock/turin2d24tm3-2l
        run: GOOS=linux GOARCH=arm GOARM=7,softfloat go build -ldflags="-s -w"
